#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: themath_development

test:
  <<: *default
  database: themath_test

production:
  <<: *default
  database: themath_production
  username: themath
  password: <%= ENV['THEMATH_DATABASE_PASSWORD'] %>
