# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

defaults: &defaults
  protocol: "http"
  domain: "http://themath-api.herokuapp.com"
  domain_friendly: "HAID"
  company_name: "How Am I Doing, LLC"
  company_address: "893 Bergen St. Unit 7 Brooklyn NY 11238"
  company_email_legal: "hello@howamidoingapp.com"
  email_from: <%= ENV["EMAIL_FROM_ADDRESS"] || "HAID <hello@howamidoingapp.com>" %>
  hashids_salt: bdf05920422f13ea7a3e0c80f57851e8b8693d71059654ffe0f539b9d50dd9768cce33575ed7aeedfae7a210d3589c8454a255238b58795021845b63e83838e8

development:
  <<: *defaults
  domain: "<%= ENV['DOMAIN'] || 'localhost:3000' %>"
  secret_key_base: fc842aec0aa6f4afa539bd34eadc79b21d5912c0a6ffca840311132dc4021034f4f08d7cf346e5917eaaf3f5384f3a536b46c10f280b35c0be193b3f1456a12c

test:
  <<: *defaults
  domain: "example.com"
  secret_key_base: ec1c55ba0495548cb2def60e4745dd88388cd9f1b7bed2373c18ea3f5955a47f8f84cc87b5ae30558e97d0089f165f5c3b3dcbc5fed59a1f9b000fa58322176d

production:
  <<: *defaults
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
